language: node_js
node_js: stable
install: true
script:
- chmod 755 ./travis.sh
- "./travis.sh"
deploy:
  provider: releases
  user: $user
  password: $password
  skip_cleanup: true
  # api_key:
  #    secure: "gOJpPn6WM56g5nDdhYaDpMXWKlI9OSrqw1eNNSBPyNJFfkhsTu0JnxCFCIgFDJHHmZtT5qZ/ew0TVFFQpdgQ9TGQmv8AzVEQNwB50dyc/bpBXI/dBwPTK02h6+IDif/YpICIPowwI81Gi/zcNCtbXttfnK4INLAdPY1QLmc9VQ2WltTqPnLSggHelyese80MZqbMirqb87JAzxRRclek+2iSyQ0RBMHP0doboq4HBPpxj1W/CD/t66sIGi4n+qdMj2AYQR8Qw2XYlAkkCYz0yN5j0y+COu8AD7jGYaGgkz6H0nYPQJlYXEtakrBCpwVyaCreDn29KY99ezpjGgkhM/XQJkHf33sj7/Wd3VgVylxS1ajNEz9GgJXM54SkKooQmeOddyEww9DvFRTW74hXNWn3c5RCgbBXi1RYvJXs5AtM1O8ejAxMk5iKlsI1a5QXQhmgYa2u/7OYBqskeyRaW3oULOCAStEGr12IJ1GtHILFtT/nya197efP9tLuuPm5/SYHtS54uAzi3jXv2/o8qW4xEsZZuWZBDoTQVBpkFGVT83DxBR7EHoo8ewQnWwVU1ImjKrxHoxwATzJFw5UzsTQqrjf6xRdi
  on:
    repo: monkeyMall/kefu-webim
    tags: true