language: node_js
node_js: stable
install: true
script:
- chmod 755 ./travis.sh
- "./travis.sh"
deploy:
  provider: releases
  api_key:
    # secure: jZknOSyxex1wy6aDsWYmdZKY/mFA2orE+tuHfGAgXmbNBtgW0T3vQ78yIkJWekkLy6LeDGpTkaOmLQ39TSaGh62JI0Ycp+tnidM00N7QobygR2ciGPL+PosKE67I/zIuI/VY1ILoAOGQUapdhBPiPJji57HyyC0cxwmKMKgJCZabqUhyFp0StGmLFpW0Eq8GzqvqSpzTIrDOZFzROBUEuMKtKMeofzVsnHjEAa71yYa71qQ4pGtIG1CAgt3BzdQhBKR6r8L+B7b/1z2fOvv4XkJvpkY/jYA9PI4c23Lu8pQfSs9wPbx6BkpisUH4IVNaSpCGfLZgcZyhIbu4rm9+YshIUdJwEnTsJ3TELE8c1h9aoEdYgrnkQNVbex0YAPZ+mkU6PXqPcDYOHLBTcYTNoP4rzO8YJbhb/6MwmMogn1vjeDZsyQqaejgN3YCGO5ZMkrDmWS3z68tX0SLZFnv3lDpE0FbbPw3BaF39aLqsybqR1S3BrqZylmtvfSk08hR24JJGsPNcv5+Afte++xQH1gbVqLadnSUq/2zAq+DyWwzm8MX2N2+vEREXO3VQWToRY0GFDxSlZFECgzdprCgrB36UQ0i0oZ3UfZ+n7r3h+lVTTTRQ9upr66En6iMtVS21WVOZJpnSvjhdVbUMNtFHk5medVHTXijQIVuA7aFjOJs=
    secure: "PTrSj0mvsey0hySH5Kg4dFsuI3zGOLwTdgz13UJn5v9B96n6Z4463h0S2aX7wNgQQ1YwuzxCp8szf6kCOkAzuM+b8lRi3vZUhqPSxYLtiA7D9mTVLykBG6HQisshnej+YqMT1Q+GNmMLkbr1OSsCXoaZFugLKTxbq+zcu4WTFJ5ODCqmyj5RWvMA165druYyIDR4h069qc8/8IDfpRy4UAk+kdBaClkPBriu1KiwYpxSd1GbJrAHgV8BO2KiMdsoy7XTYLXKyiq7lauM6HXaEq/oeAWXXHOyy52GVq+UFRijG+MX/3pRRYAH3osnhcOBrmJ2y8HH+j/DdOu5jfbqQM/e9zwKLadPVlAz8SBCrFcMBQVLHu5aqW3GayuOR9Ac3wKYxR7QC2G6RUtjEb5DHZu+xChDirfMAVdXzIhvMckAca1sd0cFwtL4Xi8A/y6I/Iba6AAlWHv3wI2O01431DG/P2lkmj16fXb8g09TCWE6jlSRnYYUCWGe9cPLjfaeXx/HSNs8Bbb82OrioTjkQcv77u1J3DYSv5v9ipyaK3RzEy4NYzKtrRPa158eOggO8ybgwfE3lr9KK4pSgoQl9hc+uQAY7Cls95HygCSTPMlJVkH3IhwqdMzv6/pcfx2vXlOZXZxnjANc1GFkX8DXbMcAubUOhNDmqCDjSv4bWAs="
  file: "*.tar.gz"
  skip_cleanup: true
  on:
    repo: monkeyMall/kefu-webim
    tags: true
