language: node_js
node_js: stable
install: true
script:
- chmod 755 ./travis.sh
- "./travis.sh"
deploy:
  provider: releases
  api_key: ${github_oauth}
  # file: $TRAVIS_BUILD_DIR
  skip_cleanup: true
  on:
    all_branches: true
    tag: true
